INSERT INTO animal VALUES(1, 'Galapagos Penguin', 'exotic', 1);
INSERT INTO animal VALUES(2, 'Emperor Penguin', 'rare', 1);
INSERT INTO animal VALUES(3, 'Sri Lankan sloth bear', 'exotic', 3);
INSERT INTO animal VALUES(4, 'Grizzly bear', 'common', 3);
INSERT INTO animal VALUES(5, 'Giant Panda bear', 'exotic', 2);
INSERT INTO animal VALUES(6, 'Florida black bear', 'rare', 2);
INSERT INTO animal VALUES(7, 'Siberian tiger', 'rare', 4);
INSERT INTO animal VALUES(8, 'Bengal tiger', 'common', 3);
INSERT INTO animal VALUES(9, 'South China tiger', 'exotic', 2);
INSERT INTO animal VALUES(10, 'Alpaca', 'common', 1);
INSERT INTO animal VALUES(11, 'Llama', NULL, 3);
