INSERT INTO bed VALUES('B01', 101, 'Intensive Care Unit', NULL, NULL);
INSERT INTO bed VALUES('B02', 102, 'Intensive Care Unit', NULL, NULL);
INSERT INTO bed VALUES('B03', 103, 'Intensive Care Unit', 'P01', 'N03');
INSERT INTO bed VALUES('B04', 104, 'Intensive Care Unit', NULL, NULL);
INSERT INTO bed VALUES('B05', 105, 'Intensive Care Unit', NULL, NULL);
INSERT INTO bed VALUES('B06', 106, 'Intensive Care Unit', NULL, NULL);
INSERT INTO bed VALUES('B07', 107, 'Intensive Care Unit', 'P04', 'N09');
INSERT INTO bed VALUES('B08', 108, 'Intensive Care Unit', NULL, NULL);
INSERT INTO bed VALUES('B09', 109, 'Intensive Care Unit', 'P07', 'N02');
INSERT INTO bed VALUES('B10', 110, 'Intensive Care Unit', NULL, NULL);
INSERT INTO bed VALUES('B11', 201, 'Surgery', NULL, NULL);
INSERT INTO bed VALUES('B12', 202, 'Surgery', NULL, NULL);
INSERT INTO bed VALUES('B13', 203, 'Surgery', 'P13', 'N03');
INSERT INTO bed VALUES('B14', 204, 'Surgery', NULL, NULL);
INSERT INTO bed VALUES('B15', 206, 'Surgery', 'P03', 'N04');
INSERT INTO bed VALUES('B16', 207, 'Surgery', NULL, NULL);
INSERT INTO bed VALUES('B17', 208, 'Surgery', NULL, NULL);
INSERT INTO bed VALUES('B18', 206, 'Surgery', NULL, NULL);
INSERT INTO bed VALUES('B19', 207, 'Surgery', NULL, NULL);
INSERT INTO bed VALUES('B20', 208, 'Surgery', NULL, NULL);
INSERT INTO bed VALUES('B21', 1001, 'Rehabilitation', NULL, NULL);
INSERT INTO bed VALUES('B22', 1011, 'Rehabilitation', NULL, NULL);
INSERT INTO bed VALUES('B23', 1022, 'Rehabilitation', NULL, NULL);
INSERT INTO bed VALUES('B24', 1033, 'Rehabilitation', 'P09', 'N04');
INSERT INTO bed VALUES('B25', 1045, 'Rehabilitation', NULL, NULL);
INSERT INTO bed VALUES('B26', 1203, 'Long-Term Care', NULL, NULL);
INSERT INTO bed VALUES('B27', 1212, 'Long-Term Care', NULL, NULL);
INSERT INTO bed VALUES('B28', 1224, 'Long-Term Care', 'P11', 'N04');
INSERT INTO bed VALUES('B29', 1233, 'Long-Term Care', NULL, NULL);
INSERT INTO bed VALUES('B30', 1250, 'Long-Term Care', NULL, NULL);
commit;