
DROP table TIMECARD;

DROP table BED;

DROP table PATIENT;

DROP table NURSE;

DROP table PHYSICIAN;


--This structuring is the exact structuring to use to populate the database
--Physician, Timecard, Nurse, Patient, Bed
CREATE TABLE PHYSICIAN(
    D_ID VARCHAR2(3),
    D_NAME VARCHAR2(25) NOT NULL,
    D_SPECIALTY VARCHAR2(20),
        CONSTRAINT PHYSICIAN_PK PRIMARY KEY(D_ID) 
);

CREATE TABLE TIMECARD(
    D_ID VARCHAR2(3),
    T_DATE DATE,
    T_HOURS NUMBER(2),
        CONSTRAINT TIMECARD_PK PRIMARY KEY(D_ID, T_DATE)
);

CREATE TABLE NURSE(
    N_ID VARCHAR2(3),
    N_NAME VARCHAR2(25) NOT NULL,
    N_SALARY NUMBER(7),
    SUPERVISOR_ID VARCHAR2(3),
        CONSTRAINT NURSE_PK PRIMARY KEY(N_ID),
        CONSTRAINT SUPERVISOR_ID FOREIGN KEY(N_ID) REFERENCES NURSE(N_ID)
);

CREATE TABLE PATIENT(
    P_NUMBER VARCHAR2(3),
    P_NAME VARCHAR2(25) NOT NULL,
    P_AGE NUMBER(3),
    D_ID VARCHAR2(3),
        CONSTRAINT PATIENT_PK PRIMARY KEY(P_NUMBER),
        CONSTRAINT PHYSICIAN_FK FOREIGN KEY(D_ID) REFERENCES PHYSICIAN(D_ID)
);

CREATE TABLE BED(
    B_NUMBER VARCHAR2(3),
    R_NUMBER NUMBER(4),
    UNIT VARCHAR2(25),
    P_NUMBER VARCHAR2(3),
    N_ID VARCHAR2(3),
        CONSTRAINT BED_PK PRIMARY KEY(B_NUMBER),
        CONSTRAINT PATIENT_FK FOREIGN KEY(P_NUMBER) REFERENCES PATIENT(P_NUMBER),
        CONSTRAINT NURSE_FK FOREIGN KEY(N_ID) REFERENCES NURSE(N_ID)
);

