INSERT INTO patient VALUES('P01', 'Taylor Swift', 32, 'D01');
INSERT INTO patient VALUES('P02', 'Bruno Mars', 31, 'D04');
INSERT INTO patient VALUES('P03', 'Justin Bieber', 29, 'D07');
INSERT INTO patient VALUES('P04', 'Adele', 34, 'D10');
INSERT INTO patient VALUES('P05', 'Lady Gaga', 35, 'D02');
INSERT INTO patient VALUES('P06', 'Katy Perry', 33, 'D05');
INSERT INTO patient VALUES('P07', 'Rihanna', 34, 'D08');
INSERT INTO patient VALUES('P08', 'Snoop Dogg', 45, 'D11');
INSERT INTO patient VALUES('P09', 'Ariana Grande', 27, 'D12');
INSERT INTO patient VALUES('P10', 'Alicia Keys', 36, 'D01');
INSERT INTO patient VALUES('P11', 'Post Malone', 29, 'D02');
INSERT INTO patient VALUES('P12', 'Beyonce', 37, 'D05');
INSERT INTO patient VALUES('P13', 'Britney Spears', 38, 'D08');
commit;