INSERT INTO physician VALUES('D01', 'Will Smith', 'Dermatology');
INSERT INTO physician VALUES('D02', 'Margot Robbie', 'Anesthesiology');
INSERT INTO physician VALUES('D03', 'Ryan Gosling', 'Family Medicine');
INSERT INTO physician VALUES('D04', 'Dwayne Johnson', 'Surgery');
INSERT INTO physician VALUES('D05', 'Emma Stone', 'Internal medicine');
INSERT INTO physician VALUES('D06', 'Tom Hanks', 'Dermatology');
INSERT INTO physician VALUES('D07', 'Idris Elba', 'Anesthesiology');
INSERT INTO physician VALUES('D08', 'Gal Gadot', 'Family Medicine');
INSERT INTO physician VALUES('D09', 'Will Ferrell', 'Internal medicine');
INSERT INTO physician VALUES('D10', 'Chris Evans', 'Dermatology');
INSERT INTO physician VALUES('D11', 'Jamie Foxx', 'Surgery');
INSERT INTO physician VALUES('D12', 'Tom Hardy', 'Anesthesiology');
commit;